### ISSUE TITLE
Questions regarding differences between the paper and the code

### ISSUE THREAD

**Issue by shenberg** [exercise-book-yq/Supercodec#1]
Hi,

Thank you for both the paper and the code! It was interesting to read and looks like it may be better than EnCodec.

I have a few questions when I was looking at the implementation versus the paper:

1. I noticed that despite the drawing in Fig. 1, an LSTM is not being used. Am I right? I looked for references to SLSTM and LSTM and there were none except in `lstm.py` - does this reflect the model evaluated in the paper?
2. It seems like the selective feature fusion network is also unused in the released code: both in `SBMP_Encoder` and `SBMP_Decoder`, the `SelectNet` member is not used. See for example [Line 312](https://github.com/exercise-book-yq/Supercodec/blob/8d13a32ec2ea5fa045a8d1230f91ce0b4c07f682/supercodec.py#L312) where the output is generated by summing the streams. The same happens in the decoder block. Does this match the model in the paper?
3. It seems that the residual blocks you used, `ResBlock1` and `ResBlock2`, include non-causal convolutions. Does this reflect the model evaluated in the paper? If so, did you compare your results to a non-causal Encodec (`ResidualUnit` is causal)? Arguably this could be the source of the advantage you show relative to Encodec, and not the architectural details.

**Comment by exercise-book-yq** [comment]
1. This model didn't use the LSTM like Encodec. I would like to do some experiments on it.
2. Sorry, I will update it.
3. We compare this model with baselines, all non-causal, including Encodec.

**Comment by shenberg** [comment]
Thanks for the quick response!
