### ISSUE TITLE
Question about the checkpoint.

### ISSUE THREAD

**Issue by isjwdu** [exercise-book-yq/Supercodec#2]
Do you have any plans to release checkpoints?

**Comment by exercise-book-yq** [comment]
We will release the checkpoint trained on Librispeech as soon as possible.

**Comment by exercise-book-yq** [comment]
We have provided a pretrained model at 1 kbps in https://drive.google.com/drive/folders/1Bjgqfhv6EwR3APPO0nfWwlwVRECjzCx1?usp=drive_link.
